"""add relationships

Revision ID: 05e749b2adb1
Revises: 5acfe8794247
Create Date: 2025-08-30 22:31:53.839872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05e749b2adb1'
down_revision: Union[str, Sequence[str], None] = '5acfe8794247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('posts_username_key'), 'posts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('posts_username_key'), 'posts', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('posts', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
