"""add username

Revision ID: 7b8692aa7445
Revises: 2dbaca4eba90
Create Date: 2025-08-30 20:46:51.865891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8692aa7445'
down_revision: Union[str, Sequence[str], None] = '2dbaca4eba90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('username', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'posts', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'username')
    # ### end Alembic commands ###
